name: FarmZone
version: '1.0-SNAPSHOT'
main: org.Vertyx.farmZone.FarmZoneMain
api-version: '1.21'
commands:
  farmzone:
    description: Create a new safe Area
  debugfz:
    description: debug my plugin
