name: FarmZone
version: '1.0-SNAPSHOT'
main: org.Vertyx.farmzone.FarmzoneMain
api-version: '1.21'
commands:
  farmzone:
    description: create, delete, bossbarcolor, showbossbar, hidebossbar
  home:
    description: Teleports you to your homezone